### ISSUE TITLE
can you please upgrade your plugin to support new Ionic Push urls?

### ISSUE THREAD

**Issue by ofershap** [benrondeau/Ionic-Push-Notification-NodeJS-Server#7]
Ionic v2.0 beta has been released with new urls, can you please kindly update your plugin to support new urls?

http://docs.ionic.io/v2.0.0-beta/docs/api-push

Thanks

**Comment by pradel** [comment]
@spi7fire you can check https://www.npmjs.com/package/ionic-push who use the latest api

**Comment by benrondeau** [comment]
Updated. Please try now
